.TH BACKUP 1 "" "Version 1.0"
.SH NAME
backup \- a simple program for backing up files or folders.
.SH SYNOPSIS
backup

Before this program is run you will need to make changes to the
.B config/conf
file in order to choose what you would like backup.  If nothing is specified in the conf file... nothing will be backed up.
.SH EXAMPLES
.SS How to Run this Program

If you are using Bash, you should be able to use: ./backup

If you aren't using Bash, you might be able to use: bash backup
.SH AUTHOR
summea
