.TH DB-BACKUP 1 "" "Version 1.0"
.SH NAME
db-backup \- a simple program for backing up databases.
.SH SYNOPSIS
db-backup

Before this program is run you will need to make changes to the
.B config/conf
file in order to choose what databases you would like backup.  If nothing is specified in the conf file... nothing will be backed up.
.SH EXAMPLES
.SS How to Run this Program

If you are using Bash, you should be able to use: ./db-backup

If you aren't using Bash, you might be able to use: bash db-backup
.SH AUTHOR
summea
